### PR TITLE
Topic/server process test

### LINKED ISSUE #13: Simple server_process test
The Travis build should start a simple server, and confirm that basic routes work. See [this test](https://github.com/forensic-architecture/timemap/blob/develop/test/server_process.js) in timemap as a reference.

Setting this up here is a touch more involved, as the server currently needs a connection with a google sheet to be of any use; which in turn requires a service account private key and email that is authenticated on the sheet from which it is pulling data.

Two solutions I can think of here:
 1. explore Travis private variables, and set the build up with a private key and email to test.
 2. Is there a way to access a public sheet through the [sheets API](https://developers.google.com/sheets/api/) without a service account? In this case we could test on a public sheet.
 3. Create a dummy config with no sheets, to bypass this connection, and very simply test whether the server builds and runs.

The easiest step forward is number 3, I think.

### LINKED ISSUE #21: Better test suite
The test suite is bare bones at the moment. Ideally, the test suite would check that all routes work, returning valid messages, errors, or data. 

This should be more intuitive with 72edac9 now merged.

### PR DESCRIPTION
**Pull request by breezykermo**
Continued from @jlieb10's welcome contribution on #31.
closes #13 closes #21.

I had a proper play with Travis, and better understand how it works now. I've also:
 * fixed a typo in the lint script that wasn't linting tests
 * linted all the tests
 * modified the logic in the serverProcess.js test that @jlieb10 wrote to leverage Ava's async features, and ensure that some tests run before others. It is crucial, for example, that `/api/update` runs before any of the routes are tested, otherwise there will be no data in the server.
 * refactored the encrypting logic to a script, and moved it to a pre-push hook, rather than a pre-commit.

I'm still not going to quite merge this PR, as I want to add some structure in the .env file to allow for different credentials for different sheet backends. That requires a little bit more thinking through the scope of this project.

### CODE REVIEW

**Comment by breezykermo** [comment]
also the build failed: so I'll have to bicker with Travis about what's going on there.

**Comment by breezykermo** [comment]
I've moved it to a pre-push hook, so that the encrypted `.env.enc` is only computed and added once, in an additional commit (that only contains the new encrypted value) before pushing from local to remote. This saves having to run the encryption on every local commit, as we only actually need the `.env.enc` in git when pushing to the remote, so that Travis can run with it.

**Comment by breezykermo** [comment]
I've removed travis-ci.ORG from this repo for the time being, so that only travis-ci.COM builds trigger. I don't think this is a sustainable solution, though. My understanding is that .ORG is the solution for open source projects, and that .COM is a purchased service, and that the 'Forensic Architecture' organisation is currently running a trial that runs out after 100 builds.

If I'm right with these details above, we'll have to find another solution so that we can do everything through .ORG.

**Comment by jlieb10** [comment]
For me, it builds on .org but fails on .com because my Travis account is
not professional tier/paid. I suspect once FA's 100 build trial runs out it
will run fine on .org and fail on .com - the encryption option works on
both tiers.

**Comment by breezykermo** [comment]
Weird. I've removed .COM now and tinkering to see if I can get a passing build on .ORG

**Comment by jlieb10** [comment]
Good find

**Comment by breezykermo** [comment]
@jlieb10 -- does this script work to encrypt the private key for you, with passing tests on Travis? I'm trying to work out whether it is necessary to include additional checks in the bash script to query whether the user has commit access to this root repo, or whether the script works with Travis for forked repos as is.

**Comment by jlieb10** [comment]
I will have a few free hours to contribute later today. Will let you know
then.

**Comment by breezykermo** [comment]
Awesome. I've added a hacky check to only require travis encryption for maintainers (contributors with forensic-architecture/datasheet-server as their origin), so that newcomers don't necessarily need to install travis to make a commit. Once these builds pass we'll be good to merge, thanks for all this work @jlieb10 !

**Comment by breezykermo** [comment]
Just added another commit that refactors the encrypt operation out of the pre-commit hook, and turns it into a manual NPM command that is run before push.

**Pull request merged**
